export const POLLING_INTERVALS = {
  FAST: 1000, // 1 second
  NORMAL: 2000, // 2 seconds
  DEFAULT: 5000, // 5 seconds
  SLOW: 10000, // 10 seconds
} as const;

export const DEFAULT_POLLING_INTERVAL_MS = POLLING_INTERVALS.NORMAL;
export const POLLING_INTERVAL_MS = POLLING_INTERVALS.DEFAULT;
export const GRAPH_REFRESH_INTERVAL_MS = POLLING_INTERVALS.SLOW;
